support for number of multiple entries
avantifellows/auth-to-bigquery pull request #4
Opened 2021-11-09 06:51 UTC by sudheshna-donthineni

Whenever a user enters multiple inputs, all the ID's get recorded in BQ. But there was no information about which ID's were typed together or to figure out how much this feature is being used. 

This code stores the length of the user values, which contains each ID and its valid flag, in BQ. 
Example of how the input to the lambda looks like: 
`
{'dateTime': '2021-11-03T08:49:39.365Z', 'purpose': {'type': 'staging', 'subType': 'liveclass', 'params': {'platform': 'meet', 'id': 'eig-ioxa-rvj'}}, 'authType': 'SRN', 'user': {'values': [{'userID': '1111111111', 'valid': True}, {'userID': '1231231231', 'valid': False}, {'userID': '1111111110', 'valid': True}]}} | {'dateTime': '2021-11-03T08:49:39.365Z', 'purpose': {'type': 'staging', 'subType': 'liveclass', 'params': {'platform': 'meet', 'id': 'eig-ioxa-rvj'}}, 'authType': 'SRN', 'user': {'values': [{'userID': '1111111111', 'valid': True}, {'userID': '1231231231', 'valid': False}, {'userID': '1111111110', 'valid': True}]}}
`

2021-11-09 06:57 UTC, pritamps requested changes
Just some small stuff :)

2021-11-09 06:57 UTC, pritamps commented on lambda_function.py
> +                # extract all ID's in the array
Remove apostrophe here :)

2021-11-09 06:57 UTC, pritamps commented on lambda_function.py
> +                    row["number_of_multiple_entries"] = user_values_length
Why not just `number_of_entries`?

2021-11-09 08:44 UTC, deepansh96 commented on lambda_function.py
> +                user_values_length = len(user_values)
I dont think this variable is needed really, can just do with `len(user_values)`

2021-11-09 08:45 UTC, deepansh96 commented on lambda_function.py
> +                for i in range(user_values_length):
```suggestion
                for i in range(len(user_values)):
```

2021-11-09 08:45 UTC, deepansh96 commented on lambda_function.py
> +                    row["number_of_multiple_entries"] = user_values_length
```suggestion
                    row["number_of_multiple_entries"] = len(user_values)
```

2021-11-10 09:46 UTC, deepansh96 approved these changes

2021-11-16 14:51 UTC, merged